version: "3.9"
services:
  web:
    build: .
    command: sh -c './wait-for pgdb:5432 -- ./main'
    ports:
      - "3000:3000"
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      PG_HOST: "pgdb"
      PG_PORT: "5432"
      PG_USER: "testuser"
      PG_PASS: "testpass"
      PG_DB: "sensor_cloud"
      PORT: "3000"
    depends_on:
      - redis
      - pgdb
  redis:
    image: "redis:alpine"
  pgdb:
    image: "postgres:12"
    environment:
      POSTGRES_DATABASE: "sensor_cloud"
      POSTGRES_USER: "testuser"
      POSTGRES_PASSWORD: "testpass"
      POSTGRES_ROOT_PASSWORD: "root"
    ports:
      - "5432:5432"
